# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# Basic IG metadata
id: bha-ig
canonical: http://bha.colorado.gov/fhir/bha-ig
name: BHAIG
title: "Colorado BHA FHIR Implementation Guide"
description: "A FHIR implementation guide to enable standardized behavioral health data exchange and reduce provider administrative burden throughout Colorado's behavioral health ecosystem"
status: active
version: 0.1.0-current  # using semver. The "-current" is used for CI builds.
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#840'

# Publisher information
publisher:
  name: Colorado Behavioral Health Administration
  url: https://bha.colorado.gov
  email: cdhs_bha_provider_support@state.co.us
extension: 
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 0
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm-support
    valueMarkdown: |
      This is a work in progress, and not yet ready for production use.
      It is intended to be used for testing and development purposes only.

# Dependencies
dependencies:
  hl7.fhir.us.core: 
    version: 6.1.0
    id: uscore
  hl7.fhir.us.military-service: 1.0.0
  hl7.fhir.uv.sdc: 3.0.0
  
# Global settings
parameters: # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  show-inherited-invariants: false
  usage-stats-opt-out: true
  shownav: true
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  apply-version: true
  pin-canonicals: pin-multiples
  fmm-definition: maturity.html
  propagate-status: true

# Pages structure
pages:
  index.md:
    title: Home
    generation: markdown
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
  guidance.md:
    title: Implementation Guidance
    generation: markdown
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: normative
  profiles.md:
    title: Profiles
    generation: markdown
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
  questionnaires.md:
    title: Questionnaires
    generation: markdown
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
  terminology.md:
    title: Terminology
    generation: markdown
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
  about.md:
    title: About
    generation: markdown
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
  maturity.md:
    title: Redefined FMM
    generation: markdown
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative
  questions.md:
    title: Questions
    generation: markdown
    extension: 
      - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
        valueCode: informative

menu:
  Home: index.html
  Guidance: guidance.html
  Profiles: profiles.html
  Questionnaires: questionnaires.html
  Terminology: terminology.html
  Artifacts: artifacts.html
  About: 
    About: about.html
    Maturity: maturity.html
    Questions: questions.html
    
